// auto-generated by scripts/build_dashboard_data.py — do not edit by hand
const DASH = {
 "unit": "papers",
 "areas": [
  {
   "code": "D1",
   "name": "Logic & Advanced CMOS Devices",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D2",
   "name": "Memory Devices & Technology",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D3",
   "name": "Interconnect, Packaging & 3D Integration",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D4",
   "name": "Process, Materials & Metrology",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D5",
   "name": "Device Modeling, Simulation & Reliability",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D6",
   "name": "Power, RF & Analog Devices",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D7",
   "name": "Optoelectronics, Display & Image Sensors",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D8",
   "name": "Sensors, MEMS & Bio-devices",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D9",
   "name": "Emerging & Beyond-CMOS Devices",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "C1",
   "name": "Digital Processors & AI Accelerators",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C2",
   "name": "Data Converters & Analog Circuits",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C3",
   "name": "RF, mmWave & Wireless Transceivers",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C4",
   "name": "Wireline & Optical I/O",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C5",
   "name": "Power Management Circuits",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C6",
   "name": "Security & Hardware Trust",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C7",
   "name": "Biomedical & Wearable Circuits",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C8",
   "name": "Design Methodology, EDA & CAD",
   "tier": "Circuits & Systems"
  },
  {
   "code": "X1",
   "name": "Neuromorphic & In-Memory Computing",
   "tier": "Cross-cutting / Emerging Computing"
  },
  {
   "code": "X2",
   "name": "Quantum & Cryogenic Technology",
   "tier": "Cross-cutting / Emerging Computing"
  }
 ],
 "seasons": [
  "S2023-24",
  "S2024-25",
  "S2025-26"
 ],
 "overseas": [
  "IEDM",
  "ISSCC",
  "VLSI"
 ],
 "domestic": [
  "KCS"
 ],
 "bySeasonAll": {
  "D1": {
   "S2023-24": 80,
   "S2024-25": 64,
   "S2025-26": 71
  },
  "D2": {
   "S2023-24": 162,
   "S2024-25": 206,
   "S2025-26": 190
  },
  "D3": {
   "S2023-24": 43,
   "S2024-25": 75,
   "S2025-26": 80
  },
  "D4": {
   "S2023-24": 113,
   "S2024-25": 110,
   "S2025-26": 100
  },
  "D5": {
   "S2023-24": 51,
   "S2024-25": 30,
   "S2025-26": 92
  },
  "D6": {
   "S2023-24": 55,
   "S2024-25": 70,
   "S2025-26": 42
  },
  "D7": {
   "S2023-24": 83,
   "S2024-25": 97,
   "S2025-26": 86
  },
  "D8": {
   "S2023-24": 42,
   "S2024-25": 64,
   "S2025-26": 60
  },
  "D9": {
   "S2023-24": 46,
   "S2024-25": 69,
   "S2025-26": 125
  },
  "C1": {
   "S2023-24": 86,
   "S2024-25": 85,
   "S2025-26": 105
  },
  "C2": {
   "S2023-24": 67,
   "S2024-25": 81,
   "S2025-26": 41
  },
  "C3": {
   "S2023-24": 83,
   "S2024-25": 82,
   "S2025-26": 117
  },
  "C4": {
   "S2023-24": 31,
   "S2024-25": 37,
   "S2025-26": 30
  },
  "C5": {
   "S2023-24": 40,
   "S2024-25": 51,
   "S2025-26": 46
  },
  "C6": {
   "S2023-24": 17,
   "S2024-25": 26,
   "S2025-26": 16
  },
  "C7": {
   "S2023-24": 31,
   "S2024-25": 52,
   "S2025-26": 54
  },
  "C8": {
   "S2023-24": 22,
   "S2024-25": 4,
   "S2025-26": 14
  },
  "X1": {
   "S2023-24": 68,
   "S2024-25": 46,
   "S2025-26": 49
  },
  "X2": {
   "S2023-24": 41,
   "S2024-25": 48,
   "S2025-26": 31
  }
 },
 "bySeasonDomestic": {
  "D1": {
   "S2023-24": 18,
   "S2024-25": 7,
   "S2025-26": 14
  },
  "D2": {
   "S2023-24": 47,
   "S2024-25": 72,
   "S2025-26": 72
  },
  "D3": {
   "S2023-24": 24,
   "S2024-25": 25,
   "S2025-26": 35
  },
  "D4": {
   "S2023-24": 103,
   "S2024-25": 100,
   "S2025-26": 100
  },
  "D5": {
   "S2023-24": 33,
   "S2024-25": 21,
   "S2025-26": 49
  },
  "D6": {
   "S2023-24": 30,
   "S2024-25": 37,
   "S2025-26": 35
  },
  "D7": {
   "S2023-24": 38,
   "S2024-25": 51,
   "S2025-26": 15
  },
  "D8": {
   "S2023-24": 17,
   "S2024-25": 17,
   "S2025-26": 16
  },
  "D9": {
   "S2023-24": 26,
   "S2024-25": 45,
   "S2025-26": 94
  },
  "C1": {
   "S2023-24": 10,
   "S2024-25": 12,
   "S2025-26": 24
  },
  "C2": {
   "S2023-24": 6,
   "S2024-25": 5,
   "S2025-26": 0
  },
  "C3": {
   "S2023-24": 4,
   "S2024-25": 9,
   "S2025-26": 4
  },
  "C4": {
   "S2023-24": 0,
   "S2024-25": 0,
   "S2025-26": 0
  },
  "C5": {
   "S2023-24": 0,
   "S2024-25": 0,
   "S2025-26": 0
  },
  "C6": {
   "S2023-24": 0,
   "S2024-25": 7,
   "S2025-26": 0
  },
  "C7": {
   "S2023-24": 5,
   "S2024-25": 4,
   "S2025-26": 4
  },
  "C8": {
   "S2023-24": 22,
   "S2024-25": 4,
   "S2025-26": 14
  },
  "X1": {
   "S2023-24": 21,
   "S2024-25": 18,
   "S2025-26": 0
  },
  "X2": {
   "S2023-24": 15,
   "S2024-25": 27,
   "S2025-26": 8
  }
 },
 "bySeasonOverseas": {
  "D1": {
   "S2023-24": 62,
   "S2024-25": 57,
   "S2025-26": 57
  },
  "D2": {
   "S2023-24": 115,
   "S2024-25": 134,
   "S2025-26": 118
  },
  "D3": {
   "S2023-24": 19,
   "S2024-25": 50,
   "S2025-26": 45
  },
  "D4": {
   "S2023-24": 10,
   "S2024-25": 10,
   "S2025-26": 0
  },
  "D5": {
   "S2023-24": 18,
   "S2024-25": 9,
   "S2025-26": 43
  },
  "D6": {
   "S2023-24": 25,
   "S2024-25": 33,
   "S2025-26": 7
  },
  "D7": {
   "S2023-24": 45,
   "S2024-25": 46,
   "S2025-26": 71
  },
  "D8": {
   "S2023-24": 25,
   "S2024-25": 47,
   "S2025-26": 44
  },
  "D9": {
   "S2023-24": 20,
   "S2024-25": 24,
   "S2025-26": 31
  },
  "C1": {
   "S2023-24": 76,
   "S2024-25": 73,
   "S2025-26": 81
  },
  "C2": {
   "S2023-24": 61,
   "S2024-25": 76,
   "S2025-26": 41
  },
  "C3": {
   "S2023-24": 79,
   "S2024-25": 73,
   "S2025-26": 113
  },
  "C4": {
   "S2023-24": 31,
   "S2024-25": 37,
   "S2025-26": 30
  },
  "C5": {
   "S2023-24": 40,
   "S2024-25": 51,
   "S2025-26": 46
  },
  "C6": {
   "S2023-24": 17,
   "S2024-25": 19,
   "S2025-26": 16
  },
  "C7": {
   "S2023-24": 26,
   "S2024-25": 48,
   "S2025-26": 50
  },
  "C8": {
   "S2023-24": 0,
   "S2024-25": 0,
   "S2025-26": 0
  },
  "X1": {
   "S2023-24": 47,
   "S2024-25": 28,
   "S2025-26": 49
  },
  "X2": {
   "S2023-24": 26,
   "S2024-25": 21,
   "S2025-26": 23
  }
 },
 "byConf": {
  "D1": {
   "IEDM": 110,
   "ISSCC": 0,
   "VLSI": 66,
   "KCS": 39
  },
  "D2": {
   "IEDM": 198,
   "ISSCC": 47,
   "VLSI": 122,
   "KCS": 191
  },
  "D3": {
   "IEDM": 67,
   "ISSCC": 8,
   "VLSI": 39,
   "KCS": 84
  },
  "D4": {
   "IEDM": 6,
   "ISSCC": 0,
   "VLSI": 14,
   "KCS": 303
  },
  "D5": {
   "IEDM": 62,
   "ISSCC": 0,
   "VLSI": 8,
   "KCS": 103
  },
  "D6": {
   "IEDM": 52,
   "ISSCC": 4,
   "VLSI": 9,
   "KCS": 102
  },
  "D7": {
   "IEDM": 70,
   "ISSCC": 51,
   "VLSI": 41,
   "KCS": 104
  },
  "D8": {
   "IEDM": 48,
   "ISSCC": 54,
   "VLSI": 14,
   "KCS": 50
  },
  "D9": {
   "IEDM": 58,
   "ISSCC": 0,
   "VLSI": 17,
   "KCS": 165
  },
  "C1": {
   "IEDM": 11,
   "ISSCC": 137,
   "VLSI": 82,
   "KCS": 46
  },
  "C2": {
   "IEDM": 0,
   "ISSCC": 109,
   "VLSI": 69,
   "KCS": 11
  },
  "C3": {
   "IEDM": 28,
   "ISSCC": 184,
   "VLSI": 53,
   "KCS": 17
  },
  "C4": {
   "IEDM": 0,
   "ISSCC": 60,
   "VLSI": 38,
   "KCS": 0
  },
  "C5": {
   "IEDM": 1,
   "ISSCC": 95,
   "VLSI": 41,
   "KCS": 0
  },
  "C6": {
   "IEDM": 8,
   "ISSCC": 30,
   "VLSI": 14,
   "KCS": 7
  },
  "C7": {
   "IEDM": 14,
   "ISSCC": 66,
   "VLSI": 44,
   "KCS": 13
  },
  "C8": {
   "IEDM": 0,
   "ISSCC": 0,
   "VLSI": 0,
   "KCS": 40
  },
  "X1": {
   "IEDM": 66,
   "ISSCC": 39,
   "VLSI": 19,
   "KCS": 39
  },
  "X2": {
   "IEDM": 37,
   "ISSCC": 15,
   "VLSI": 18,
   "KCS": 50
  }
 },
 "totalAll": {
  "D1": 215,
  "D2": 558,
  "D3": 198,
  "D4": 323,
  "D5": 173,
  "D6": 167,
  "D7": 266,
  "D8": 166,
  "D9": 240,
  "C1": 276,
  "C2": 189,
  "C3": 282,
  "C4": 98,
  "C5": 137,
  "C6": 59,
  "C7": 137,
  "C8": 40,
  "X1": 163,
  "X2": 120
 },
 "totalDomestic": {
  "D1": 39,
  "D2": 191,
  "D3": 84,
  "D4": 303,
  "D5": 103,
  "D6": 102,
  "D7": 104,
  "D8": 50,
  "D9": 165,
  "C1": 46,
  "C2": 11,
  "C3": 17,
  "C4": 0,
  "C5": 0,
  "C6": 7,
  "C7": 13,
  "C8": 40,
  "X1": 39,
  "X2": 50
 },
 "totalOverseas": {
  "D1": 176,
  "D2": 367,
  "D3": 114,
  "D4": 20,
  "D5": 70,
  "D6": 65,
  "D7": 162,
  "D8": 116,
  "D9": 75,
  "C1": 230,
  "C2": 178,
  "C3": 265,
  "C4": 98,
  "C5": 137,
  "C6": 52,
  "C7": 124,
  "C8": 0,
  "X1": 124,
  "X2": 70
 },
 "grandDomestic": 1364,
 "grandOverseas": 2443,
 "confTotals": {
  "IEDM": 854,
  "ISSCC": 932,
  "VLSI": 744,
  "KCS": 1373
 }
};
