// auto-generated by scripts/build_dashboard_data.py — do not edit by hand
const DASH = {
 "areas": [
  {
   "code": "D1",
   "name": "Logic & Advanced CMOS Devices",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D2",
   "name": "Memory Devices & Technology",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D3",
   "name": "Interconnect, Packaging & 3D Integration",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D4",
   "name": "Process, Materials & Metrology",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D5",
   "name": "Device Modeling, Simulation & Reliability",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D6",
   "name": "Power, RF & Analog Devices",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D7",
   "name": "Optoelectronics, Display & Image Sensors",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D8",
   "name": "Sensors, MEMS & Bio-devices",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "D9",
   "name": "Emerging & Beyond-CMOS Devices",
   "tier": "Devices & Process Technology"
  },
  {
   "code": "C1",
   "name": "Digital Processors & AI Accelerators",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C2",
   "name": "Data Converters & Analog Circuits",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C3",
   "name": "RF, mmWave & Wireless Transceivers",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C4",
   "name": "Wireline & Optical I/O",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C5",
   "name": "Power Management Circuits",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C6",
   "name": "Security & Hardware Trust",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C7",
   "name": "Biomedical & Wearable Circuits",
   "tier": "Circuits & Systems"
  },
  {
   "code": "C8",
   "name": "Design Methodology, EDA & CAD",
   "tier": "Circuits & Systems"
  },
  {
   "code": "X1",
   "name": "Neuromorphic & In-Memory Computing",
   "tier": "Cross-cutting / Emerging Computing"
  },
  {
   "code": "X2",
   "name": "Quantum & Cryogenic Technology",
   "tier": "Cross-cutting / Emerging Computing"
  }
 ],
 "seasons": [
  "S2023-24",
  "S2024-25",
  "S2025-26"
 ],
 "overseas": [
  "IEDM",
  "ISSCC",
  "VLSI"
 ],
 "domestic": [
  "KCS"
 ],
 "bySeasonAll": {
  "D1": {
   "S2023-24": 14,
   "S2024-25": 9,
   "S2025-26": 11
  },
  "D2": {
   "S2023-24": 27,
   "S2024-25": 33,
   "S2025-26": 31
  },
  "D3": {
   "S2023-24": 7,
   "S2024-25": 11,
   "S2025-26": 13
  },
  "D4": {
   "S2023-24": 20,
   "S2024-25": 19,
   "S2025-26": 17
  },
  "D5": {
   "S2023-24": 8,
   "S2024-25": 4,
   "S2025-26": 15
  },
  "D6": {
   "S2023-24": 9,
   "S2024-25": 10,
   "S2025-26": 8
  },
  "D7": {
   "S2023-24": 13,
   "S2024-25": 15,
   "S2025-26": 14
  },
  "D8": {
   "S2023-24": 6,
   "S2024-25": 9,
   "S2025-26": 9
  },
  "D9": {
   "S2023-24": 9,
   "S2024-25": 11,
   "S2025-26": 20
  },
  "C1": {
   "S2023-24": 15,
   "S2024-25": 13,
   "S2025-26": 15
  },
  "C2": {
   "S2023-24": 10,
   "S2024-25": 14,
   "S2025-26": 8
  },
  "C3": {
   "S2023-24": 12,
   "S2024-25": 13,
   "S2025-26": 18
  },
  "C4": {
   "S2023-24": 5,
   "S2024-25": 5,
   "S2025-26": 4
  },
  "C5": {
   "S2023-24": 5,
   "S2024-25": 8,
   "S2025-26": 6
  },
  "C6": {
   "S2023-24": 2,
   "S2024-25": 4,
   "S2025-26": 2
  },
  "C7": {
   "S2023-24": 4,
   "S2024-25": 9,
   "S2025-26": 8
  },
  "C8": {
   "S2023-24": 4,
   "S2024-25": 1,
   "S2025-26": 3
  },
  "X1": {
   "S2023-24": 10,
   "S2024-25": 7,
   "S2025-26": 8
  },
  "X2": {
   "S2023-24": 8,
   "S2024-25": 8,
   "S2025-26": 6
  }
 },
 "bySeasonDomestic": {
  "D1": {
   "S2023-24": 3,
   "S2024-25": 1,
   "S2025-26": 2
  },
  "D2": {
   "S2023-24": 8,
   "S2024-25": 11,
   "S2025-26": 12
  },
  "D3": {
   "S2023-24": 4,
   "S2024-25": 4,
   "S2025-26": 6
  },
  "D4": {
   "S2023-24": 18,
   "S2024-25": 17,
   "S2025-26": 17
  },
  "D5": {
   "S2023-24": 5,
   "S2024-25": 3,
   "S2025-26": 8
  },
  "D6": {
   "S2023-24": 5,
   "S2024-25": 6,
   "S2025-26": 6
  },
  "D7": {
   "S2023-24": 6,
   "S2024-25": 8,
   "S2025-26": 3
  },
  "D8": {
   "S2023-24": 3,
   "S2024-25": 3,
   "S2025-26": 3
  },
  "D9": {
   "S2023-24": 5,
   "S2024-25": 8,
   "S2025-26": 15
  },
  "C1": {
   "S2023-24": 2,
   "S2024-25": 2,
   "S2025-26": 4
  },
  "C2": {
   "S2023-24": 1,
   "S2024-25": 1,
   "S2025-26": 0
  },
  "C3": {
   "S2023-24": 1,
   "S2024-25": 2,
   "S2025-26": 1
  },
  "C4": {
   "S2023-24": 0,
   "S2024-25": 0,
   "S2025-26": 0
  },
  "C5": {
   "S2023-24": 0,
   "S2024-25": 0,
   "S2025-26": 0
  },
  "C6": {
   "S2023-24": 0,
   "S2024-25": 1,
   "S2025-26": 0
  },
  "C7": {
   "S2023-24": 1,
   "S2024-25": 1,
   "S2025-26": 1
  },
  "C8": {
   "S2023-24": 4,
   "S2024-25": 1,
   "S2025-26": 3
  },
  "X1": {
   "S2023-24": 3,
   "S2024-25": 3,
   "S2025-26": 0
  },
  "X2": {
   "S2023-24": 3,
   "S2024-25": 5,
   "S2025-26": 2
  }
 },
 "bySeasonOverseas": {
  "D1": {
   "S2023-24": 11,
   "S2024-25": 8,
   "S2025-26": 9
  },
  "D2": {
   "S2023-24": 19,
   "S2024-25": 22,
   "S2025-26": 19
  },
  "D3": {
   "S2023-24": 3,
   "S2024-25": 7,
   "S2025-26": 7
  },
  "D4": {
   "S2023-24": 2,
   "S2024-25": 2,
   "S2025-26": 0
  },
  "D5": {
   "S2023-24": 3,
   "S2024-25": 1,
   "S2025-26": 7
  },
  "D6": {
   "S2023-24": 4,
   "S2024-25": 4,
   "S2025-26": 2
  },
  "D7": {
   "S2023-24": 7,
   "S2024-25": 7,
   "S2025-26": 11
  },
  "D8": {
   "S2023-24": 3,
   "S2024-25": 6,
   "S2025-26": 6
  },
  "D9": {
   "S2023-24": 4,
   "S2024-25": 3,
   "S2025-26": 5
  },
  "C1": {
   "S2023-24": 13,
   "S2024-25": 11,
   "S2025-26": 11
  },
  "C2": {
   "S2023-24": 9,
   "S2024-25": 13,
   "S2025-26": 8
  },
  "C3": {
   "S2023-24": 11,
   "S2024-25": 11,
   "S2025-26": 17
  },
  "C4": {
   "S2023-24": 5,
   "S2024-25": 5,
   "S2025-26": 4
  },
  "C5": {
   "S2023-24": 5,
   "S2024-25": 8,
   "S2025-26": 6
  },
  "C6": {
   "S2023-24": 2,
   "S2024-25": 3,
   "S2025-26": 2
  },
  "C7": {
   "S2023-24": 3,
   "S2024-25": 8,
   "S2025-26": 7
  },
  "C8": {
   "S2023-24": 0,
   "S2024-25": 0,
   "S2025-26": 0
  },
  "X1": {
   "S2023-24": 7,
   "S2024-25": 4,
   "S2025-26": 8
  },
  "X2": {
   "S2023-24": 5,
   "S2024-25": 3,
   "S2025-26": 4
  }
 },
 "byConf": {
  "D1": {
   "IEDM": 14,
   "ISSCC": 0,
   "VLSI": 14,
   "KCS": 6
  },
  "D2": {
   "IEDM": 28,
   "ISSCC": 6,
   "VLSI": 26,
   "KCS": 31
  },
  "D3": {
   "IEDM": 9,
   "ISSCC": 1,
   "VLSI": 7,
   "KCS": 14
  },
  "D4": {
   "IEDM": 1,
   "ISSCC": 0,
   "VLSI": 3,
   "KCS": 52
  },
  "D5": {
   "IEDM": 9,
   "ISSCC": 0,
   "VLSI": 2,
   "KCS": 16
  },
  "D6": {
   "IEDM": 7,
   "ISSCC": 1,
   "VLSI": 2,
   "KCS": 17
  },
  "D7": {
   "IEDM": 10,
   "ISSCC": 5,
   "VLSI": 10,
   "KCS": 17
  },
  "D8": {
   "IEDM": 7,
   "ISSCC": 5,
   "VLSI": 3,
   "KCS": 9
  },
  "D9": {
   "IEDM": 8,
   "ISSCC": 0,
   "VLSI": 4,
   "KCS": 28
  },
  "C1": {
   "IEDM": 2,
   "ISSCC": 14,
   "VLSI": 19,
   "KCS": 8
  },
  "C2": {
   "IEDM": 0,
   "ISSCC": 14,
   "VLSI": 16,
   "KCS": 2
  },
  "C3": {
   "IEDM": 4,
   "ISSCC": 23,
   "VLSI": 12,
   "KCS": 4
  },
  "C4": {
   "IEDM": 0,
   "ISSCC": 6,
   "VLSI": 8,
   "KCS": 0
  },
  "C5": {
   "IEDM": 0,
   "ISSCC": 10,
   "VLSI": 9,
   "KCS": 0
  },
  "C6": {
   "IEDM": 1,
   "ISSCC": 3,
   "VLSI": 3,
   "KCS": 1
  },
  "C7": {
   "IEDM": 2,
   "ISSCC": 6,
   "VLSI": 10,
   "KCS": 3
  },
  "C8": {
   "IEDM": 0,
   "ISSCC": 0,
   "VLSI": 0,
   "KCS": 8
  },
  "X1": {
   "IEDM": 11,
   "ISSCC": 4,
   "VLSI": 4,
   "KCS": 6
  },
  "X2": {
   "IEDM": 6,
   "ISSCC": 2,
   "VLSI": 4,
   "KCS": 10
  }
 },
 "totalAll": {
  "D1": 34,
  "D2": 91,
  "D3": 31,
  "D4": 56,
  "D5": 27,
  "D6": 27,
  "D7": 42,
  "D8": 24,
  "D9": 40,
  "C1": 43,
  "C2": 32,
  "C3": 43,
  "C4": 14,
  "C5": 19,
  "C6": 8,
  "C7": 21,
  "C8": 8,
  "X1": 25,
  "X2": 22
 },
 "totalDomestic": {
  "D1": 6,
  "D2": 31,
  "D3": 14,
  "D4": 52,
  "D5": 16,
  "D6": 17,
  "D7": 17,
  "D8": 9,
  "D9": 28,
  "C1": 8,
  "C2": 2,
  "C3": 4,
  "C4": 0,
  "C5": 0,
  "C6": 1,
  "C7": 3,
  "C8": 8,
  "X1": 6,
  "X2": 10
 },
 "totalOverseas": {
  "D1": 28,
  "D2": 60,
  "D3": 17,
  "D4": 4,
  "D5": 11,
  "D6": 10,
  "D7": 25,
  "D8": 15,
  "D9": 12,
  "C1": 35,
  "C2": 30,
  "C3": 39,
  "C4": 14,
  "C5": 19,
  "C6": 7,
  "C7": 18,
  "C8": 0,
  "X1": 19,
  "X2": 12
 },
 "grandDomestic": 232,
 "grandOverseas": 375,
 "confTotals": {
  "IEDM": 121,
  "ISSCC": 107,
  "VLSI": 162,
  "KCS": 232
 }
};
