// auto-generated by scripts/parse_institutions.py
const INST = {
 "areaNames": {
  "D1": "Logic & Advanced CMOS Devices",
  "D2": "Memory Devices & Technology",
  "D3": "Interconnect, Packaging & 3D Integration",
  "D4": "Process, Materials & Metrology",
  "D5": "Device Modeling, Simulation & Reliability",
  "D6": "Power, RF & Analog Devices",
  "D7": "Optoelectronics, Display & Image Sensors",
  "D8": "Sensors, MEMS & Bio-devices",
  "D9": "Emerging & Beyond-CMOS Devices",
  "C1": "Digital Processors & AI Accelerators",
  "C2": "Data Converters & Analog Circuits",
  "C3": "RF, mmWave & Wireless Transceivers",
  "C4": "Wireline & Optical I/O",
  "C5": "Power Management Circuits",
  "C6": "Security & Hardware Trust",
  "C7": "Biomedical & Wearable Circuits",
  "C8": "Design Methodology, EDA & CAD",
  "X1": "Neuromorphic & In-Memory Computing",
  "X2": "Quantum & Cryogenic Technology",
  "SP": "Plenary / Invited / Panel / Showcase"
 },
 "korByConf": {
  "IEDM": {
   "kor": 169,
   "tot": 854
  },
  "ISSCC": {
   "kor": 175,
   "tot": 950
  },
  "VLSI": {
   "kor": 197,
   "tot": 776
  }
 },
 "korByArea": {
  "D1": {
   "kor": 30,
   "tot": 180
  },
  "D2": {
   "kor": 147,
   "tot": 372
  },
  "D3": {
   "kor": 21,
   "tot": 118
  },
  "D4": {
   "kor": 5,
   "tot": 21
  },
  "D5": {
   "kor": 8,
   "tot": 71
  },
  "D6": {
   "kor": 8,
   "tot": 66
  },
  "D7": {
   "kor": 53,
   "tot": 166
  },
  "D8": {
   "kor": 12,
   "tot": 116
  },
  "D9": {
   "kor": 11,
   "tot": 75
  },
  "C1": {
   "kor": 47,
   "tot": 235
  },
  "C2": {
   "kor": 31,
   "tot": 179
  },
  "C3": {
   "kor": 34,
   "tot": 269
  },
  "C4": {
   "kor": 15,
   "tot": 100
  },
  "C5": {
   "kor": 34,
   "tot": 137
  },
  "C6": {
   "kor": 8,
   "tot": 52
  },
  "C7": {
   "kor": 27,
   "tot": 127
  },
  "X1": {
   "kor": 25,
   "tot": 125
  },
  "X2": {
   "kor": 8,
   "tot": 71
  },
  "SP": {
   "kor": 16,
   "tot": 71
  }
 },
 "korByConfYear": {
  "IEDM": {
   "2023": {
    "kor": 50,
    "tot": 243
   },
   "2024": {
    "kor": 52,
    "tot": 318
   },
   "2025": {
    "kor": 67,
    "tot": 293
   }
  },
  "ISSCC": {
   "2024": {
    "kor": 60,
    "tot": 301
   },
   "2025": {
    "kor": 57,
    "tot": 309
   },
   "2026": {
    "kor": 58,
    "tot": 340
   }
  },
  "VLSI": {
   "2023": {
    "kor": 60,
    "tot": 243
   },
   "2024": {
    "kor": 64,
    "tot": 248
   },
   "2025": {
    "kor": 73,
    "tot": 285
   }
  }
 },
 "topInstitutions": [
  [
   "Samsung",
   247
  ],
  [
   "KAIST",
   80
  ],
  [
   "SK hynix",
   65
  ],
  [
   "POSTECH",
   58
  ],
  [
   "Seoul Nat'l Univ",
   34
  ],
  [
   "Yonsei Univ",
   24
  ],
  [
   "Sogang Univ",
   24
  ],
  [
   "Hanyang Univ",
   22
  ],
  [
   "Korea Univ",
   19
  ],
  [
   "UNIST",
   18
  ],
  [
   "Sungkyunkwan(SKKU)",
   16
  ],
  [
   "Kyungpook Nat'l",
   11
  ],
  [
   "Inha Univ",
   5
  ],
  [
   "GIST",
   5
  ],
  [
   "KIST",
   4
  ],
  [
   "Kyung Hee",
   4
  ],
  [
   "NNFC",
   2
  ],
  [
   "Sejong Univ",
   2
  ],
  [
   "Pusan Nat'l",
   2
  ],
  [
   "Ewha",
   1
  ]
 ],
 "instTypeName": {
  "Samsung": "company",
  "SK hynix": "company",
  "LG": "company",
  "DB HiTek": "company",
  "Magnachip": "company",
  "KAIST": "university",
  "POSTECH": "university",
  "Seoul Nat'l Univ": "university",
  "Yonsei Univ": "university",
  "Korea Univ": "university",
  "Hanyang Univ": "university",
  "Sungkyunkwan(SKKU)": "university",
  "UNIST": "university",
  "GIST": "university",
  "DGIST": "university",
  "Ewha": "university",
  "Sogang Univ": "university",
  "Kyung Hee": "university",
  "Pusan Nat'l": "university",
  "Kyungpook Nat'l": "university",
  "Inha Univ": "university",
  "Ajou Univ": "university",
  "Chung-Ang": "university",
  "Konkuk": "university",
  "Sejong Univ": "university",
  "Kookmin": "university",
  "ETRI": "institute",
  "KIST": "institute",
  "KERI": "institute",
  "KRISS": "institute",
  "NNFC": "institute"
 },
 "typeMix": {
  "company": 304,
  "university": 274,
  "institute": 8
 },
 "areaTopInst": {
  "D1": [
   [
    "Samsung",
    17
   ],
   [
    "SK hynix",
    6
   ],
   [
    "UNIST",
    4
   ]
  ],
  "D2": [
   [
    "Samsung",
    90
   ],
   [
    "SK hynix",
    28
   ],
   [
    "POSTECH",
    17
   ]
  ],
  "D3": [
   [
    "Samsung",
    10
   ],
   [
    "KAIST",
    4
   ],
   [
    "Hanyang Univ",
    2
   ]
  ],
  "D4": [
   [
    "Samsung",
    3
   ],
   [
    "SK hynix",
    1
   ],
   [
    "POSTECH",
    1
   ]
  ],
  "D5": [
   [
    "KAIST",
    5
   ],
   [
    "Samsung",
    5
   ],
   [
    "Seoul Nat'l Univ",
    1
   ]
  ],
  "D6": [
   [
    "Samsung",
    4
   ],
   [
    "KAIST",
    2
   ],
   [
    "Inha Univ",
    1
   ]
  ],
  "D7": [
   [
    "Samsung",
    22
   ],
   [
    "Sungkyunkwan(SKKU)",
    9
   ],
   [
    "KAIST",
    8
   ]
  ],
  "D8": [
   [
    "Samsung",
    3
   ],
   [
    "Seoul Nat'l Univ",
    2
   ],
   [
    "POSTECH",
    1
   ]
  ],
  "D9": [
   [
    "Samsung",
    6
   ],
   [
    "POSTECH",
    3
   ],
   [
    "SK hynix",
    2
   ]
  ],
  "C1": [
   [
    "KAIST",
    11
   ],
   [
    "POSTECH",
    7
   ],
   [
    "Seoul Nat'l Univ",
    6
   ]
  ],
  "C2": [
   [
    "Samsung",
    14
   ],
   [
    "Seoul Nat'l Univ",
    4
   ],
   [
    "KAIST",
    4
   ]
  ],
  "C3": [
   [
    "Samsung",
    16
   ],
   [
    "KAIST",
    7
   ],
   [
    "Hanyang Univ",
    2
   ]
  ],
  "C4": [
   [
    "Samsung",
    8
   ],
   [
    "KAIST",
    2
   ],
   [
    "POSTECH",
    2
   ]
  ],
  "C5": [
   [
    "Samsung",
    14
   ],
   [
    "Sogang Univ",
    10
   ],
   [
    "Korea Univ",
    3
   ]
  ],
  "C6": [
   [
    "Samsung",
    5
   ],
   [
    "POSTECH",
    3
   ],
   [
    "KAIST",
    1
   ]
  ],
  "C7": [
   [
    "KAIST",
    4
   ],
   [
    "Samsung",
    4
   ],
   [
    "POSTECH",
    4
   ]
  ],
  "X1": [
   [
    "Samsung",
    6
   ],
   [
    "KAIST",
    6
   ],
   [
    "SK hynix",
    5
   ]
  ],
  "X2": [
   [
    "Samsung",
    4
   ],
   [
    "KAIST",
    3
   ],
   [
    "SK hynix",
    1
   ]
  ],
  "SP": [
   [
    "Samsung",
    9
   ],
   [
    "SK hynix",
    4
   ],
   [
    "POSTECH",
    1
   ]
  ]
 }
};
