// auto-generated by scripts/build_keywords.py
const KW = {
 "groups": {
  "Gate-All-Around": "Logic/Device",
  "CFET": "Logic/Device",
  "Nanosheet": "Logic/Device",
  "FinFET": "Logic/Device",
  "Forksheet": "Logic/Device",
  "DTCO/STCO": "Logic/Device",
  "Backside PDN": "Logic/Device",
  "Monolithic 3D": "Logic/Device",
  "2D material": "Logic/Device",
  "Carbon nanotube": "Logic/Device",
  "DRAM": "Memory",
  "NAND": "Memory",
  "SRAM": "Memory",
  "MRAM": "Memory",
  "RRAM": "Memory",
  "PCM": "Memory",
  "FeRAM/FeFET": "Memory",
  "HBM": "Memory",
  "CXL": "Memory",
  "Embedded memory": "Memory",
  "Chiplet": "Packaging",
  "Heterogeneous integ.": "Packaging",
  "Advanced packaging": "Packaging",
  "Hybrid bonding": "Packaging",
  "TSV/Interposer": "Packaging",
  "EUV/Litho": "Process",
  "Etch": "Process",
  "ALD/CVD": "Process",
  "Epitaxy": "Process",
  "Oxide semiconductor": "Process",
  "High-k": "Process",
  "GaN": "Power/RF",
  "SiC": "Power/RF",
  "Wide bandgap": "Power/RF",
  "HEMT": "Power/RF",
  "mmWave/THz": "Power/RF",
  "RF transceiver": "Power/RF",
  "Silicon photonics": "Power/RF",
  "LiDAR": "Power/RF",
  "Image sensor": "Sensor/Bio",
  "Display": "Sensor/Bio",
  "MEMS": "Sensor/Bio",
  "Biosensor": "Sensor/Bio",
  "AI accelerator": "Compute/AI",
  "Compute-in-memory": "Compute/AI",
  "Neuromorphic": "Compute/AI",
  "LLM/Transformer": "Compute/AI",
  "ADC/DAC": "Circuit",
  "PLL/Clock": "Circuit",
  "SerDes/Wireline": "Circuit",
  "Power mgmt (DC-DC/LDO)": "Circuit",
  "Quantum/Qubit": "Quantum",
  "Cryogenic": "Quantum",
  "Security/PUF": "Security",
  "Reliability": "Reliability",
  "TCAD/Modeling": "Reliability"
 },
 "labels": [
  "Gate-All-Around",
  "CFET",
  "Nanosheet",
  "FinFET",
  "Forksheet",
  "DTCO/STCO",
  "Backside PDN",
  "Monolithic 3D",
  "2D material",
  "Carbon nanotube",
  "DRAM",
  "NAND",
  "SRAM",
  "MRAM",
  "RRAM",
  "PCM",
  "FeRAM/FeFET",
  "HBM",
  "CXL",
  "Embedded memory",
  "Chiplet",
  "Heterogeneous integ.",
  "Advanced packaging",
  "Hybrid bonding",
  "TSV/Interposer",
  "EUV/Litho",
  "Etch",
  "ALD/CVD",
  "Epitaxy",
  "Oxide semiconductor",
  "High-k",
  "GaN",
  "SiC",
  "Wide bandgap",
  "HEMT",
  "mmWave/THz",
  "RF transceiver",
  "Silicon photonics",
  "LiDAR",
  "Image sensor",
  "Display",
  "MEMS",
  "Biosensor",
  "AI accelerator",
  "Compute-in-memory",
  "Neuromorphic",
  "LLM/Transformer",
  "ADC/DAC",
  "PLL/Clock",
  "SerDes/Wireline",
  "Power mgmt (DC-DC/LDO)",
  "Quantum/Qubit",
  "Cryogenic",
  "Security/PUF",
  "Reliability",
  "TCAD/Modeling"
 ],
 "hitsGroup": {
  "Gate-All-Around": {
   "overseas": 36,
   "domestic": 36
  },
  "CFET": {
   "overseas": 25,
   "domestic": 18
  },
  "Nanosheet": {
   "overseas": 40,
   "domestic": 30
  },
  "FinFET": {
   "overseas": 45,
   "domestic": 8
  },
  "Forksheet": {
   "overseas": 2,
   "domestic": 7
  },
  "DTCO/STCO": {
   "overseas": 11,
   "domestic": 4
  },
  "Backside PDN": {
   "overseas": 25,
   "domestic": 10
  },
  "Monolithic 3D": {
   "overseas": 49,
   "domestic": 24
  },
  "2D material": {
   "overseas": 12,
   "domestic": 45
  },
  "Carbon nanotube": {
   "overseas": 14,
   "domestic": 28
  },
  "DRAM": {
   "overseas": 45,
   "domestic": 86
  },
  "NAND": {
   "overseas": 36,
   "domestic": 70
  },
  "SRAM": {
   "overseas": 36,
   "domestic": 15
  },
  "MRAM": {
   "overseas": 34,
   "domestic": 3
  },
  "RRAM": {
   "overseas": 47,
   "domestic": 45
  },
  "PCM": {
   "overseas": 10,
   "domestic": 9
  },
  "FeRAM/FeFET": {
   "overseas": 106,
   "domestic": 187
  },
  "HBM": {
   "overseas": 6,
   "domestic": 13
  },
  "CXL": {},
  "Embedded memory": {
   "overseas": 11,
   "domestic": 3
  },
  "Chiplet": {
   "overseas": 22,
   "domestic": 4
  },
  "Heterogeneous integ.": {
   "overseas": 4,
   "domestic": 2
  },
  "Advanced packaging": {
   "overseas": 14,
   "domestic": 8
  },
  "Hybrid bonding": {
   "overseas": 8,
   "domestic": 32
  },
  "TSV/Interposer": {
   "overseas": 12,
   "domestic": 11
  },
  "EUV/Litho": {
   "overseas": 4,
   "domestic": 61
  },
  "Etch": {
   "overseas": 6,
   "domestic": 52
  },
  "ALD/CVD": {
   "overseas": 21,
   "domestic": 184
  },
  "Epitaxy": {
   "overseas": 7,
   "domestic": 31
  },
  "Oxide semiconductor": {
   "overseas": 68,
   "domestic": 149
  },
  "High-k": {
   "overseas": 5,
   "domestic": 36
  },
  "GaN": {
   "overseas": 73,
   "domestic": 92
  },
  "SiC": {
   "overseas": 22,
   "domestic": 43
  },
  "Wide bandgap": {
   "overseas": 6,
   "domestic": 7
  },
  "HEMT": {
   "overseas": 12,
   "domestic": 18
  },
  "mmWave/THz": {
   "overseas": 20,
   "domestic": 9
  },
  "RF transceiver": {
   "overseas": 114,
   "domestic": 38
  },
  "Silicon photonics": {
   "overseas": 23,
   "domestic": 13
  },
  "LiDAR": {
   "overseas": 20,
   "domestic": 7
  },
  "Image sensor": {
   "overseas": 72,
   "domestic": 32
  },
  "Display": {
   "overseas": 13,
   "domestic": 58
  },
  "MEMS": {
   "overseas": 27,
   "domestic": 10
  },
  "Biosensor": {
   "overseas": 29,
   "domestic": 62
  },
  "AI accelerator": {
   "overseas": 154,
   "domestic": 198
  },
  "Compute-in-memory": {
   "overseas": 57,
   "domestic": 38
  },
  "Neuromorphic": {
   "overseas": 25,
   "domestic": 165
  },
  "LLM/Transformer": {
   "overseas": 44,
   "domestic": 25
  },
  "ADC/DAC": {
   "overseas": 88,
   "domestic": 37
  },
  "PLL/Clock": {
   "overseas": 55,
   "domestic": 11
  },
  "SerDes/Wireline": {
   "overseas": 62,
   "domestic": 6
  },
  "Power mgmt (DC-DC/LDO)": {
   "overseas": 70,
   "domestic": 34
  },
  "Quantum/Qubit": {
   "overseas": 56,
   "domestic": 92
  },
  "Cryogenic": {
   "overseas": 42,
   "domestic": 15
  },
  "Security/PUF": {
   "overseas": 15,
   "domestic": 9
  },
  "Reliability": {
   "overseas": 71,
   "domestic": 130
  },
  "TCAD/Modeling": {
   "overseas": 25,
   "domestic": 133
  }
 },
 "hitsConf": {
  "Gate-All-Around": {
   "IEDM": 16,
   "ISSCC": 1,
   "VLSI": 19,
   "KCS": 36
  },
  "CFET": {
   "IEDM": 16,
   "VLSI": 9,
   "KCS": 18
  },
  "Nanosheet": {
   "IEDM": 21,
   "ISSCC": 1,
   "VLSI": 18,
   "KCS": 30
  },
  "FinFET": {
   "IEDM": 10,
   "ISSCC": 10,
   "VLSI": 25,
   "KCS": 8
  },
  "Forksheet": {
   "IEDM": 1,
   "VLSI": 1,
   "KCS": 7
  },
  "DTCO/STCO": {
   "IEDM": 5,
   "VLSI": 6,
   "KCS": 4
  },
  "Backside PDN": {
   "IEDM": 6,
   "VLSI": 19,
   "KCS": 10
  },
  "Monolithic 3D": {
   "IEDM": 29,
   "ISSCC": 1,
   "VLSI": 19,
   "KCS": 24
  },
  "2D material": {
   "IEDM": 10,
   "VLSI": 2,
   "KCS": 45
  },
  "Carbon nanotube": {
   "IEDM": 10,
   "VLSI": 4,
   "KCS": 28
  },
  "DRAM": {
   "IEDM": 18,
   "ISSCC": 9,
   "VLSI": 18,
   "KCS": 86
  },
  "NAND": {
   "IEDM": 19,
   "ISSCC": 4,
   "VLSI": 13,
   "KCS": 70
  },
  "SRAM": {
   "IEDM": 6,
   "ISSCC": 11,
   "VLSI": 19,
   "KCS": 15
  },
  "MRAM": {
   "IEDM": 20,
   "ISSCC": 5,
   "VLSI": 9,
   "KCS": 3
  },
  "RRAM": {
   "IEDM": 29,
   "ISSCC": 6,
   "VLSI": 12,
   "KCS": 45
  },
  "PCM": {
   "IEDM": 7,
   "VLSI": 3,
   "KCS": 9
  },
  "FeRAM/FeFET": {
   "IEDM": 74,
   "VLSI": 32,
   "KCS": 187
  },
  "HBM": {
   "IEDM": 2,
   "ISSCC": 2,
   "VLSI": 2,
   "KCS": 13
  },
  "CXL": {},
  "Embedded memory": {
   "IEDM": 5,
   "ISSCC": 2,
   "VLSI": 4,
   "KCS": 3
  },
  "Chiplet": {
   "IEDM": 6,
   "ISSCC": 7,
   "VLSI": 9,
   "KCS": 4
  },
  "Heterogeneous integ.": {
   "IEDM": 2,
   "VLSI": 2,
   "KCS": 2
  },
  "Advanced packaging": {
   "IEDM": 5,
   "ISSCC": 4,
   "VLSI": 5,
   "KCS": 8
  },
  "Hybrid bonding": {
   "IEDM": 4,
   "VLSI": 4,
   "KCS": 32
  },
  "TSV/Interposer": {
   "IEDM": 4,
   "ISSCC": 6,
   "VLSI": 2,
   "KCS": 11
  },
  "EUV/Litho": {
   "IEDM": 3,
   "VLSI": 1,
   "KCS": 61
  },
  "Etch": {
   "IEDM": 4,
   "VLSI": 2,
   "KCS": 52
  },
  "ALD/CVD": {
   "IEDM": 12,
   "VLSI": 9,
   "KCS": 184
  },
  "Epitaxy": {
   "IEDM": 2,
   "VLSI": 5,
   "KCS": 31
  },
  "Oxide semiconductor": {
   "IEDM": 40,
   "VLSI": 28,
   "KCS": 149
  },
  "High-k": {
   "IEDM": 1,
   "VLSI": 4,
   "KCS": 36
  },
  "GaN": {
   "IEDM": 51,
   "ISSCC": 10,
   "VLSI": 12,
   "KCS": 92
  },
  "SiC": {
   "IEDM": 18,
   "ISSCC": 1,
   "VLSI": 3,
   "KCS": 43
  },
  "Wide bandgap": {
   "IEDM": 4,
   "VLSI": 2,
   "KCS": 7
  },
  "HEMT": {
   "IEDM": 11,
   "VLSI": 1,
   "KCS": 18
  },
  "mmWave/THz": {
   "IEDM": 6,
   "ISSCC": 13,
   "VLSI": 1,
   "KCS": 9
  },
  "RF transceiver": {
   "IEDM": 17,
   "ISSCC": 55,
   "VLSI": 42,
   "KCS": 38
  },
  "Silicon photonics": {
   "IEDM": 14,
   "ISSCC": 3,
   "VLSI": 6,
   "KCS": 13
  },
  "LiDAR": {
   "IEDM": 2,
   "ISSCC": 14,
   "VLSI": 4,
   "KCS": 7
  },
  "Image sensor": {
   "IEDM": 26,
   "ISSCC": 21,
   "VLSI": 25,
   "KCS": 32
  },
  "Display": {
   "IEDM": 4,
   "ISSCC": 3,
   "VLSI": 6,
   "KCS": 58
  },
  "MEMS": {
   "IEDM": 12,
   "ISSCC": 10,
   "VLSI": 5,
   "KCS": 10
  },
  "Biosensor": {
   "IEDM": 6,
   "ISSCC": 19,
   "VLSI": 4,
   "KCS": 62
  },
  "AI accelerator": {
   "IEDM": 48,
   "ISSCC": 49,
   "VLSI": 57,
   "KCS": 198
  },
  "Compute-in-memory": {
   "IEDM": 19,
   "ISSCC": 13,
   "VLSI": 25,
   "KCS": 38
  },
  "Neuromorphic": {
   "IEDM": 12,
   "ISSCC": 6,
   "VLSI": 7,
   "KCS": 165
  },
  "LLM/Transformer": {
   "IEDM": 11,
   "ISSCC": 13,
   "VLSI": 20,
   "KCS": 25
  },
  "ADC/DAC": {
   "IEDM": 3,
   "ISSCC": 42,
   "VLSI": 43,
   "KCS": 37
  },
  "PLL/Clock": {
   "IEDM": 1,
   "ISSCC": 29,
   "VLSI": 25,
   "KCS": 11
  },
  "SerDes/Wireline": {
   "ISSCC": 41,
   "VLSI": 21,
   "KCS": 6
  },
  "Power mgmt (DC-DC/LDO)": {
   "IEDM": 2,
   "ISSCC": 45,
   "VLSI": 23,
   "KCS": 34
  },
  "Quantum/Qubit": {
   "IEDM": 27,
   "ISSCC": 12,
   "VLSI": 17,
   "KCS": 92
  },
  "Cryogenic": {
   "IEDM": 15,
   "ISSCC": 11,
   "VLSI": 16,
   "KCS": 15
  },
  "Security/PUF": {
   "IEDM": 5,
   "ISSCC": 4,
   "VLSI": 6,
   "KCS": 9
  },
  "Reliability": {
   "IEDM": 48,
   "VLSI": 23,
   "KCS": 130
  },
  "TCAD/Modeling": {
   "IEDM": 21,
   "VLSI": 4,
   "KCS": 133
  }
 },
 "hitsSeasonDom": {
  "Gate-All-Around": {
   "S2023-24": 8,
   "S2024-25": 5,
   "S2025-26": 23
  },
  "CFET": {
   "S2023-24": 2,
   "S2024-25": 4,
   "S2025-26": 12
  },
  "Nanosheet": {
   "S2023-24": 10,
   "S2024-25": 2,
   "S2025-26": 18
  },
  "FinFET": {
   "S2023-24": 4,
   "S2024-25": 2,
   "S2025-26": 2
  },
  "Forksheet": {
   "S2023-24": 5,
   "S2024-25": 1,
   "S2025-26": 1
  },
  "DTCO/STCO": {
   "S2023-24": 0,
   "S2024-25": 2,
   "S2025-26": 2
  },
  "Backside PDN": {
   "S2023-24": 2,
   "S2024-25": 2,
   "S2025-26": 6
  },
  "Monolithic 3D": {
   "S2023-24": 6,
   "S2024-25": 3,
   "S2025-26": 15
  },
  "2D material": {
   "S2023-24": 19,
   "S2024-25": 3,
   "S2025-26": 23
  },
  "Carbon nanotube": {
   "S2023-24": 6,
   "S2024-25": 2,
   "S2025-26": 20
  },
  "DRAM": {
   "S2023-24": 28,
   "S2024-25": 7,
   "S2025-26": 51
  },
  "NAND": {
   "S2023-24": 28,
   "S2024-25": 6,
   "S2025-26": 36
  },
  "SRAM": {
   "S2023-24": 9,
   "S2024-25": 0,
   "S2025-26": 6
  },
  "MRAM": {
   "S2023-24": 1,
   "S2024-25": 1,
   "S2025-26": 1
  },
  "RRAM": {
   "S2023-24": 10,
   "S2024-25": 3,
   "S2025-26": 32
  },
  "PCM": {
   "S2023-24": 3,
   "S2024-25": 3,
   "S2025-26": 3
  },
  "FeRAM/FeFET": {
   "S2023-24": 52,
   "S2024-25": 19,
   "S2025-26": 116
  },
  "HBM": {
   "S2023-24": 2,
   "S2024-25": 2,
   "S2025-26": 9
  },
  "CXL": {
   "S2023-24": 0,
   "S2024-25": 0,
   "S2025-26": 0
  },
  "Embedded memory": {
   "S2023-24": 1,
   "S2024-25": 0,
   "S2025-26": 2
  },
  "Chiplet": {
   "S2023-24": 3,
   "S2024-25": 0,
   "S2025-26": 1
  },
  "Heterogeneous integ.": {
   "S2023-24": 0,
   "S2024-25": 2,
   "S2025-26": 0
  },
  "Advanced packaging": {
   "S2023-24": 4,
   "S2024-25": 1,
   "S2025-26": 3
  },
  "Hybrid bonding": {
   "S2023-24": 12,
   "S2024-25": 3,
   "S2025-26": 17
  },
  "TSV/Interposer": {
   "S2023-24": 1,
   "S2024-25": 0,
   "S2025-26": 10
  },
  "EUV/Litho": {
   "S2023-24": 19,
   "S2024-25": 10,
   "S2025-26": 32
  },
  "Etch": {
   "S2023-24": 14,
   "S2024-25": 7,
   "S2025-26": 31
  },
  "ALD/CVD": {
   "S2023-24": 36,
   "S2024-25": 21,
   "S2025-26": 127
  },
  "Epitaxy": {
   "S2023-24": 5,
   "S2024-25": 4,
   "S2025-26": 22
  },
  "Oxide semiconductor": {
   "S2023-24": 40,
   "S2024-25": 26,
   "S2025-26": 83
  },
  "High-k": {
   "S2023-24": 9,
   "S2024-25": 2,
   "S2025-26": 25
  },
  "GaN": {
   "S2023-24": 30,
   "S2024-25": 11,
   "S2025-26": 51
  },
  "SiC": {
   "S2023-24": 22,
   "S2024-25": 0,
   "S2025-26": 21
  },
  "Wide bandgap": {
   "S2023-24": 1,
   "S2024-25": 2,
   "S2025-26": 4
  },
  "HEMT": {
   "S2023-24": 5,
   "S2024-25": 2,
   "S2025-26": 11
  },
  "mmWave/THz": {
   "S2023-24": 2,
   "S2024-25": 0,
   "S2025-26": 7
  },
  "RF transceiver": {
   "S2023-24": 11,
   "S2024-25": 7,
   "S2025-26": 20
  },
  "Silicon photonics": {
   "S2023-24": 6,
   "S2024-25": 2,
   "S2025-26": 5
  },
  "LiDAR": {
   "S2023-24": 3,
   "S2024-25": 0,
   "S2025-26": 4
  },
  "Image sensor": {
   "S2023-24": 14,
   "S2024-25": 5,
   "S2025-26": 13
  },
  "Display": {
   "S2023-24": 20,
   "S2024-25": 21,
   "S2025-26": 17
  },
  "MEMS": {
   "S2023-24": 5,
   "S2024-25": 2,
   "S2025-26": 3
  },
  "Biosensor": {
   "S2023-24": 26,
   "S2024-25": 8,
   "S2025-26": 28
  },
  "AI accelerator": {
   "S2023-24": 42,
   "S2024-25": 12,
   "S2025-26": 144
  },
  "Compute-in-memory": {
   "S2023-24": 12,
   "S2024-25": 3,
   "S2025-26": 23
  },
  "Neuromorphic": {
   "S2023-24": 42,
   "S2024-25": 23,
   "S2025-26": 100
  },
  "LLM/Transformer": {
   "S2023-24": 5,
   "S2024-25": 0,
   "S2025-26": 20
  },
  "ADC/DAC": {
   "S2023-24": 16,
   "S2024-25": 2,
   "S2025-26": 19
  },
  "PLL/Clock": {
   "S2023-24": 3,
   "S2024-25": 1,
   "S2025-26": 7
  },
  "SerDes/Wireline": {
   "S2023-24": 1,
   "S2024-25": 0,
   "S2025-26": 5
  },
  "Power mgmt (DC-DC/LDO)": {
   "S2023-24": 11,
   "S2024-25": 0,
   "S2025-26": 23
  },
  "Quantum/Qubit": {
   "S2023-24": 37,
   "S2024-25": 22,
   "S2025-26": 33
  },
  "Cryogenic": {
   "S2023-24": 7,
   "S2024-25": 2,
   "S2025-26": 6
  },
  "Security/PUF": {
   "S2023-24": 2,
   "S2024-25": 1,
   "S2025-26": 6
  },
  "Reliability": {
   "S2023-24": 45,
   "S2024-25": 15,
   "S2025-26": 70
  },
  "TCAD/Modeling": {
   "S2023-24": 47,
   "S2024-25": 22,
   "S2025-26": 64
  }
 },
 "hitsSeasonOvs": {
  "Gate-All-Around": {
   "S2023-24": 7,
   "S2024-25": 9,
   "S2025-26": 20
  },
  "CFET": {
   "S2023-24": 4,
   "S2024-25": 12,
   "S2025-26": 9
  },
  "Nanosheet": {
   "S2023-24": 11,
   "S2024-25": 11,
   "S2025-26": 18
  },
  "FinFET": {
   "S2023-24": 18,
   "S2024-25": 14,
   "S2025-26": 13
  },
  "Forksheet": {
   "S2023-24": 0,
   "S2024-25": 1,
   "S2025-26": 1
  },
  "DTCO/STCO": {
   "S2023-24": 5,
   "S2024-25": 0,
   "S2025-26": 6
  },
  "Backside PDN": {
   "S2023-24": 10,
   "S2024-25": 7,
   "S2025-26": 8
  },
  "Monolithic 3D": {
   "S2023-24": 13,
   "S2024-25": 9,
   "S2025-26": 27
  },
  "2D material": {
   "S2023-24": 4,
   "S2024-25": 7,
   "S2025-26": 1
  },
  "Carbon nanotube": {
   "S2023-24": 6,
   "S2024-25": 5,
   "S2025-26": 3
  },
  "DRAM": {
   "S2023-24": 18,
   "S2024-25": 14,
   "S2025-26": 13
  },
  "NAND": {
   "S2023-24": 10,
   "S2024-25": 12,
   "S2025-26": 14
  },
  "SRAM": {
   "S2023-24": 14,
   "S2024-25": 13,
   "S2025-26": 9
  },
  "MRAM": {
   "S2023-24": 13,
   "S2024-25": 13,
   "S2025-26": 8
  },
  "RRAM": {
   "S2023-24": 19,
   "S2024-25": 12,
   "S2025-26": 16
  },
  "PCM": {
   "S2023-24": 3,
   "S2024-25": 3,
   "S2025-26": 4
  },
  "FeRAM/FeFET": {
   "S2023-24": 35,
   "S2024-25": 32,
   "S2025-26": 39
  },
  "HBM": {
   "S2023-24": 2,
   "S2024-25": 1,
   "S2025-26": 3
  },
  "CXL": {
   "S2023-24": 0,
   "S2024-25": 0,
   "S2025-26": 0
  },
  "Embedded memory": {
   "S2023-24": 6,
   "S2024-25": 2,
   "S2025-26": 3
  },
  "Chiplet": {
   "S2023-24": 5,
   "S2024-25": 10,
   "S2025-26": 7
  },
  "Heterogeneous integ.": {
   "S2023-24": 1,
   "S2024-25": 2,
   "S2025-26": 1
  },
  "Advanced packaging": {
   "S2023-24": 4,
   "S2024-25": 8,
   "S2025-26": 2
  },
  "Hybrid bonding": {
   "S2023-24": 4,
   "S2024-25": 2,
   "S2025-26": 2
  },
  "TSV/Interposer": {
   "S2023-24": 5,
   "S2024-25": 5,
   "S2025-26": 2
  },
  "EUV/Litho": {
   "S2023-24": 2,
   "S2024-25": 0,
   "S2025-26": 2
  },
  "Etch": {
   "S2023-24": 3,
   "S2024-25": 2,
   "S2025-26": 1
  },
  "ALD/CVD": {
   "S2023-24": 7,
   "S2024-25": 7,
   "S2025-26": 7
  },
  "Epitaxy": {
   "S2023-24": 5,
   "S2024-25": 0,
   "S2025-26": 2
  },
  "Oxide semiconductor": {
   "S2023-24": 18,
   "S2024-25": 27,
   "S2025-26": 23
  },
  "High-k": {
   "S2023-24": 1,
   "S2024-25": 4,
   "S2025-26": 0
  },
  "GaN": {
   "S2023-24": 19,
   "S2024-25": 31,
   "S2025-26": 23
  },
  "SiC": {
   "S2023-24": 4,
   "S2024-25": 10,
   "S2025-26": 8
  },
  "Wide bandgap": {
   "S2023-24": 0,
   "S2024-25": 2,
   "S2025-26": 4
  },
  "HEMT": {
   "S2023-24": 5,
   "S2024-25": 3,
   "S2025-26": 4
  },
  "mmWave/THz": {
   "S2023-24": 8,
   "S2024-25": 4,
   "S2025-26": 8
  },
  "RF transceiver": {
   "S2023-24": 37,
   "S2024-25": 36,
   "S2025-26": 41
  },
  "Silicon photonics": {
   "S2023-24": 5,
   "S2024-25": 4,
   "S2025-26": 14
  },
  "LiDAR": {
   "S2023-24": 7,
   "S2024-25": 6,
   "S2025-26": 7
  },
  "Image sensor": {
   "S2023-24": 27,
   "S2024-25": 17,
   "S2025-26": 28
  },
  "Display": {
   "S2023-24": 2,
   "S2024-25": 3,
   "S2025-26": 8
  },
  "MEMS": {
   "S2023-24": 4,
   "S2024-25": 15,
   "S2025-26": 8
  },
  "Biosensor": {
   "S2023-24": 10,
   "S2024-25": 9,
   "S2025-26": 10
  },
  "AI accelerator": {
   "S2023-24": 50,
   "S2024-25": 39,
   "S2025-26": 65
  },
  "Compute-in-memory": {
   "S2023-24": 25,
   "S2024-25": 13,
   "S2025-26": 19
  },
  "Neuromorphic": {
   "S2023-24": 11,
   "S2024-25": 6,
   "S2025-26": 8
  },
  "LLM/Transformer": {
   "S2023-24": 11,
   "S2024-25": 12,
   "S2025-26": 21
  },
  "ADC/DAC": {
   "S2023-24": 30,
   "S2024-25": 27,
   "S2025-26": 31
  },
  "PLL/Clock": {
   "S2023-24": 14,
   "S2024-25": 22,
   "S2025-26": 19
  },
  "SerDes/Wireline": {
   "S2023-24": 16,
   "S2024-25": 27,
   "S2025-26": 19
  },
  "Power mgmt (DC-DC/LDO)": {
   "S2023-24": 25,
   "S2024-25": 20,
   "S2025-26": 25
  },
  "Quantum/Qubit": {
   "S2023-24": 17,
   "S2024-25": 16,
   "S2025-26": 23
  },
  "Cryogenic": {
   "S2023-24": 16,
   "S2024-25": 12,
   "S2025-26": 14
  },
  "Security/PUF": {
   "S2023-24": 4,
   "S2024-25": 6,
   "S2025-26": 5
  },
  "Reliability": {
   "S2023-24": 24,
   "S2024-25": 20,
   "S2025-26": 27
  },
  "TCAD/Modeling": {
   "S2023-24": 6,
   "S2024-25": 6,
   "S2025-26": 13
  }
 },
 "groupTotalDom": 2493,
 "groupTotalOvs": 1956,
 "titlesDom": 5203,
 "titlesOvs": 2530,
 "seasons": [
  "S2023-24",
  "S2024-25",
  "S2025-26"
 ]
};
